<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vehicle extends \App\Entity\Vehicle implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'Marque', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'Model', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'annee', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'Matricule', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'client', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'entretiens'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'Marque', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'Model', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'annee', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'Matricule', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'client', '' . "\0" . 'App\\Entity\\Vehicle' . "\0" . 'entretiens'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Vehicle $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getMarque(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarque', []);

        return parent::getMarque();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarque(string $Marque): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarque', [$Marque]);

        return parent::setMarque($Marque);
    }

    /**
     * {@inheritDoc}
     */
    public function getModel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModel', []);

        return parent::getModel();
    }

    /**
     * {@inheritDoc}
     */
    public function setModel(string $Model): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModel', [$Model]);

        return parent::setModel($Model);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnee(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnee', []);

        return parent::getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnee(\DateTimeInterface $annee): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnee', [$annee]);

        return parent::setAnnee($annee);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatricule(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatricule', []);

        return parent::getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatricule(string $Matricule): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatricule', [$Matricule]);

        return parent::setMatricule($Matricule);
    }

    /**
     * {@inheritDoc}
     */
    public function getClient(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', []);

        return parent::getClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setClient(?\App\Entity\User $client): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', [$client]);

        return parent::setClient($client);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntretiens(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntretiens', []);

        return parent::getEntretiens();
    }

    /**
     * {@inheritDoc}
     */
    public function addEntretien(\App\Entity\Entretien $entretien): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEntretien', [$entretien]);

        return parent::addEntretien($entretien);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEntretien(\App\Entity\Entretien $entretien): \App\Entity\Vehicle
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEntretien', [$entretien]);

        return parent::removeEntretien($entretien);
    }

}
