<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.hPntXaw' shared service.

return $this->privates['.service_locator.hPntXaw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\EntretienController::delete' => ['privates', '.service_locator.hiYEEak', 'get_ServiceLocator_HiYEEakService.php', true],
    'App\\Controller\\EntretienController::edit' => ['privates', '.service_locator.hiYEEak', 'get_ServiceLocator_HiYEEakService.php', true],
    'App\\Controller\\EntretienController::index' => ['privates', '.service_locator.xKbRCBP', 'get_ServiceLocator_XKbRCBPService.php', true],
    'App\\Controller\\EntretienController::show' => ['privates', '.service_locator.hiYEEak', 'get_ServiceLocator_HiYEEakService.php', true],
    'App\\Controller\\UserController::delete' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController::edit' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController::show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\VehicleController::delete' => ['privates', '.service_locator.HplmWV_', 'get_ServiceLocator_HplmWVService.php', true],
    'App\\Controller\\VehicleController::edit' => ['privates', '.service_locator.HplmWV_', 'get_ServiceLocator_HplmWVService.php', true],
    'App\\Controller\\VehicleController::index' => ['privates', '.service_locator.Z665FpN', 'get_ServiceLocator_Z665FpNService.php', true],
    'App\\Controller\\VehicleController::show' => ['privates', '.service_locator.HplmWV_', 'get_ServiceLocator_HplmWVService.php', true],
    'App\\Controller\\EntretienController:delete' => ['privates', '.service_locator.hiYEEak', 'get_ServiceLocator_HiYEEakService.php', true],
    'App\\Controller\\EntretienController:edit' => ['privates', '.service_locator.hiYEEak', 'get_ServiceLocator_HiYEEakService.php', true],
    'App\\Controller\\EntretienController:index' => ['privates', '.service_locator.xKbRCBP', 'get_ServiceLocator_XKbRCBPService.php', true],
    'App\\Controller\\EntretienController:show' => ['privates', '.service_locator.hiYEEak', 'get_ServiceLocator_HiYEEakService.php', true],
    'App\\Controller\\UserController:delete' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController:edit' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\UserController:show' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\VehicleController:delete' => ['privates', '.service_locator.HplmWV_', 'get_ServiceLocator_HplmWVService.php', true],
    'App\\Controller\\VehicleController:edit' => ['privates', '.service_locator.HplmWV_', 'get_ServiceLocator_HplmWVService.php', true],
    'App\\Controller\\VehicleController:index' => ['privates', '.service_locator.Z665FpN', 'get_ServiceLocator_Z665FpNService.php', true],
    'App\\Controller\\VehicleController:show' => ['privates', '.service_locator.HplmWV_', 'get_ServiceLocator_HplmWVService.php', true],
], [
    'App\\Controller\\EntretienController::delete' => '?',
    'App\\Controller\\EntretienController::edit' => '?',
    'App\\Controller\\EntretienController::index' => '?',
    'App\\Controller\\EntretienController::show' => '?',
    'App\\Controller\\UserController::delete' => '?',
    'App\\Controller\\UserController::edit' => '?',
    'App\\Controller\\UserController::show' => '?',
    'App\\Controller\\VehicleController::delete' => '?',
    'App\\Controller\\VehicleController::edit' => '?',
    'App\\Controller\\VehicleController::index' => '?',
    'App\\Controller\\VehicleController::show' => '?',
    'App\\Controller\\EntretienController:delete' => '?',
    'App\\Controller\\EntretienController:edit' => '?',
    'App\\Controller\\EntretienController:index' => '?',
    'App\\Controller\\EntretienController:show' => '?',
    'App\\Controller\\UserController:delete' => '?',
    'App\\Controller\\UserController:edit' => '?',
    'App\\Controller\\UserController:show' => '?',
    'App\\Controller\\VehicleController:delete' => '?',
    'App\\Controller\\VehicleController:edit' => '?',
    'App\\Controller\\VehicleController:index' => '?',
    'App\\Controller\\VehicleController:show' => '?',
]);
