<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.xKbRCBP' shared service.

return $this->privates['.service_locator.xKbRCBP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entretienRepository' => ['privates', 'App\\Repository\\EntretienRepository', 'getEntretienRepositoryService.php', true],
], [
    'entretienRepository' => 'App\\Repository\\EntretienRepository',
]);
