<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.hiYEEak' shared service.

return $this->privates['.service_locator.hiYEEak'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entretien' => ['privates', '.errored..service_locator.hiYEEak.App\\Entity\\Entretien', NULL, 'Cannot autowire service "debug.argument_resolver.not_tagged_controller.inner": it references class "App\\Entity\\Entretien" but no such service exists.'],
], [
    'entretien' => 'App\\Entity\\Entretien',
]);
