<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Z665FpN' shared service.

return $this->privates['.service_locator.Z665FpN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'vehicleRepository' => ['privates', 'App\\Repository\\VehicleRepository', 'getVehicleRepositoryService.php', true],
], [
    'vehicleRepository' => 'App\\Repository\\VehicleRepository',
]);
